"""
Transparency label generation (Milestone 5).

Maps a scored decision to the exact reader-facing text defined in planning.md
"Transparency Label Design". One variant per label category from scoring.py:

    likely_ai     -> "Likely AI-generated"   (High-confidence AI)
    likely_human  -> "Likely human-written"  (High-confidence human)
    uncertain     -> "Inconclusive"          (Uncertain)

`{pct}` in each template is `confidence` rendered as a whole-number percent, so
the label text CHANGES with the score rather than being fixed. The three
strings below are verbatim from planning.md — do not paraphrase them here; the
spec is the source of truth and this module just fills in the percentage.
"""

# The API contract (notes.md "POST /submit") names the variants; the internal
# scoring category maps onto those public names here.
_VARIANT_NAMES = {
    "likely_ai": "high_confidence_ai",
    "likely_human": "high_confidence_human",
    "uncertain": "uncertain",
}

# Verbatim from planning.md "Transparency Label Design". {pct} is the only
# substitution. Keep these byte-for-byte identical to the spec.
_TEMPLATES = {
    "likely_ai": (
        "**Likely AI-generated.** Our analysis indicates this content was most "
        "likely produced by an AI system (confidence: {pct}%). Two independent "
        "checks — a language-model review and a writing-structure analysis — "
        "pointed the same way. If you're the creator and believe this is wrong, "
        "you can appeal this result."
    ),
    "likely_human": (
        "**Likely human-written.** Our analysis indicates this content was most "
        "likely written by a person (confidence: {pct}%). Two independent checks "
        "agreed. No action needed."
    ),
    "uncertain": (
        "**Inconclusive.** We couldn't determine with confidence whether this "
        "content was written by a person or generated by AI (confidence: {pct}%). "
        "Our two checks disagreed or found mixed signals, so we're not making a "
        "call — please treat this as a weak signal, not a verdict."
    ),
}


def generate(label_category, confidence):
    """Build the transparency label for a scored decision.

    Args:
        label_category: one of "likely_ai" | "likely_human" | "uncertain"
            (the `label_category` from scoring.score()).
        confidence: the fused confidence in [0.5, 1.0].

    Returns:
        {"variant": <public variant name>, "text": <filled reader-facing string>}
        where the variant name is high_confidence_ai / high_confidence_human /
        uncertain (the API-contract names).
    """
    template = _TEMPLATES.get(label_category)
    if template is None:
        raise ValueError(f"Unknown label_category: {label_category!r}")
    pct = round(confidence * 100)
    return {"variant": _VARIANT_NAMES[label_category], "text": template.format(pct=pct)}


if __name__ == "__main__":
    import json

    # Verification step: produce all three variants and confirm the text matches
    # planning.md. Representative confidences chosen so each category is shown.
    samples = [
        ("likely_ai", 0.92),
        ("likely_human", 0.85),
        ("uncertain", 0.60),
    ]
    for category, confidence in samples:
        label = generate(category, confidence)
        print(f"\n=== {category} (confidence {confidence}) ===")
        print(json.dumps(label, indent=2, ensure_ascii=False))
